version: 0.1
phases:
  build:
    commands:
      - aws cloudformation package --template-file samTemplate.yml --s3-bucket ruban-serverless-api-cicd --output-template-file cfnTemplate.yml
      - cat cfnTemplate.yml
artifacts:
  type: zip
  files:
    - samTemplate.yml
    - cfnTemplate.yml