AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Sample Python Serverless Application
Resources:
  # ServerlessApi:
  #   Type: AWS::Serverless::Api
  #   Properties:
  #     StageName:
  #     EndpointConfiguration: REGIONAL
  #     DefinitionBody:
  #       openapi: 3.0.1
  #       info:
  #         title: "sampleServerlessAPI"
  #         version: '1.0'
  #         paths:
  #           "/testapi":
  #             get:
  #               httpMethod: GET
  ServerlessFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "sampleServerlessFunction"
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      MemorySize: 128
      Timeout: 30
      Events:
        TestCall:
          Type: Api
          Properties:
            Path: /testapi
            Method: get